# Generated by Django 4.2.30 on 2026-06-23 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=100)),
                ('attendance', models.FloatField()),
                ('performance_rating', models.FloatField()),
                ('experience', models.IntegerField()),
                ('salary', models.FloatField()),
                ('project_completion_rate', models.FloatField()),
            ],
        ),
    ]
